services:
  oracle-db:
    image: gvenzl/oracle-xe:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=suasenha
      - APP_USER=seu_usuario
      - APP_USER_PASSWORD=suasenha

  backend:
    build: ./seu-backend
    container_name: backend-api
    ports:
      - "8081:8081"
    depends_on:
      - oracle-db
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/XE

  frontend:
    build: ./seu-frontend
    container_name: frontend-app
    ports:
      - "80:80"
    depends_on:
      - backend